#!/usr/bin/python3
import os
import time

def measure_temp():
    temp = os.popen("vcgencmd measure_temp").readline()
    temp = temp.replace("temp=","")
    return (temp.replace("\n",""))

print("Raspberry Pi3 core CPU temperatures:")
while True:
    cstring=measure_temp()
    tempstring=cstring.replace("'C","")
    tempf = float(tempstring) * 9 / 5 + 32
    # for humans to read
    # print cstring + "  " + str(round(tempf,1)) + "'F"
    # for inputting to excel
    print (tempstring + ", " + str(round(tempf,1)))
    time.sleep(2)
    
